#!/usr/bin/env bash
# SteelCAD — one-shot production bootstrap for a fresh VPS.
#
# Runs docs/DEPLOY.md §2–§6 and §10 in order: generates secrets, applies
# migrations, starts the stack behind Caddy (automatic HTTPS), creates the
# first admin, seeds the rate table, then smoke-tests the result.
#
# Usage (from the repo root on the server):
#   ./deploy/bootstrap.sh
#
# Optional overrides:
#   SITE_ADDRESS=steelcad.example.com ./deploy/bootstrap.sh   # your own domain
#   ADMIN_EMAIL=you@example.com       ./deploy/bootstrap.sh
#
# Safe to re-run: an existing .env is never overwritten (so secrets stay
# stable), migrations are incremental, /rates/seed is idempotent, and the admin
# is only created if that email does not already exist.

set -euo pipefail

cd "$(dirname "$0")/.."

COMPOSE="docker compose -f docker-compose.prod.yml -f docker-compose.tls.yml"

say()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m!!  %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31mxx  %s\033[0m\n' "$*" >&2; exit 1; }

# ── 0. Preflight ─────────────────────────────────────────────────────
say "Checking prerequisites"
command -v docker >/dev/null || die "docker is not installed. See deploy/README.md step 2."
docker compose version >/dev/null 2>&1 || die "docker compose v2 is required (not docker-compose)."
command -v openssl >/dev/null || die "openssl is required to generate secrets."
docker info >/dev/null 2>&1 || die "cannot talk to the Docker daemon — run as a user in the 'docker' group, or with sudo."
echo "docker ok"

# ── 1. Environment file ──────────────────────────────────────────────
if [ -f .env ]; then
    say "Reusing existing .env (not overwriting — secrets stay stable)"
else
    say "Generating .env with fresh secrets"

    # Let's Encrypt will not issue for a bare IP, so a hostname is required.
    # sslip.io resolves any IP embedded in the name — a real, free hostname.
    if [ -z "${SITE_ADDRESS:-}" ]; then
        PUBLIC_IP="$(curl -fsS --max-time 10 https://api.ipify.org || true)"
        [ -n "$PUBLIC_IP" ] || die "Could not detect this server's public IP. Re-run with SITE_ADDRESS=<host> set."
        SITE_ADDRESS="${PUBLIC_IP}.sslip.io"
        echo "Detected public IP ${PUBLIC_IP} -> using ${SITE_ADDRESS}"
    fi

    umask 077   # .env holds secrets; never world-readable
    cat > .env <<EOF
# Generated by deploy/bootstrap.sh — contains live secrets, never commit.
APP_ENV=production

POSTGRES_USER=steelcad
POSTGRES_PASSWORD=$(openssl rand -hex 24)
POSTGRES_DB=steelcad
DATABASE_SSL=false

JWT_SECRET_KEY=$(openssl rand -hex 32)
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7

# Same-origin behind Caddy + nginx — no CORS entries needed.
CORS_ORIGINS=
LOG_LEVEL=INFO

# Hostname Caddy requests a TLS certificate for.
SITE_ADDRESS=${SITE_ADDRESS}

# Caddy owns :80/:443, so the frontend publishes on loopback only.
FRONTEND_PUBLISH=127.0.0.1:8080:80
EOF
    echo ".env written (mode 600)"
fi

# shellcheck disable=SC1091
set -a; . ./.env; set +a
[ -n "${SITE_ADDRESS:-}" ] || die "SITE_ADDRESS missing from .env"

# ── 2. Migrations (before serving traffic) ───────────────────────────
say "Starting database"
$COMPOSE up -d db

printf 'waiting for postgres'
for _ in $(seq 1 60); do
    if $COMPOSE exec -T db pg_isready -U "${POSTGRES_USER:-steelcad}" >/dev/null 2>&1; then
        printf ' ready\n'; break
    fi
    printf '.'; sleep 2
done
$COMPOSE exec -T db pg_isready -U "${POSTGRES_USER:-steelcad}" >/dev/null 2>&1 \
    || die "postgres did not become ready in 120s — check: $COMPOSE logs db"

say "Applying database migrations (alembic upgrade head)"
# Production does NOT run create_all — migrations are the only thing that
# builds the schema here. See CLAUDE.md "Dev vs. prod".
$COMPOSE run --rm backend alembic upgrade head

# ── 3. Start everything ──────────────────────────────────────────────
say "Building and starting the full stack"
$COMPOSE up -d --build

printf 'waiting for the API to report ready'
API_UP=0
for _ in $(seq 1 60); do
    # Checked from inside the network on the real service, so this cannot be
    # fooled by nginx's SPA fallback returning a 200 text/html shell.
    if $COMPOSE exec -T backend python -c "
import sys, urllib.request
try:
    sys.exit(0 if b'ready' in urllib.request.urlopen('http://localhost:8000/ready', timeout=3).read() else 1)
except Exception:
    sys.exit(1)
" >/dev/null 2>&1; then
        printf ' ready\n'; API_UP=1; break
    fi
    printf '.'; sleep 2
done
[ "$API_UP" = 1 ] || die "backend never became ready — check: $COMPOSE logs backend --tail 50"

# ── 4. First admin account ───────────────────────────────────────────
say "Bootstrapping the admin account"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@steelcad.local}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(openssl rand -base64 15)Aa1!}"

# Credentials are passed as container env vars and read with os.environ — NOT
# interpolated into the Python source. A password containing a quote, backslash
# or $ would otherwise corrupt the script or execute as shell.
CREATED=$($COMPOSE exec -T \
    -e SC_ADMIN_EMAIL="$ADMIN_EMAIL" \
    -e SC_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
    backend python - <<'EOF' || echo "FAILED"
import asyncio, os
from sqlalchemy import select
from app.database import async_session_factory
from app.models.user import User
from app.services.auth import hash_password

email = os.environ["SC_ADMIN_EMAIL"]
password = os.environ["SC_ADMIN_PASSWORD"]

async def main():
    async with async_session_factory() as db:
        if await db.scalar(select(User).where(User.email == email)):
            print("EXISTS")
            return
        db.add(User(
            email=email,
            name="Admin",
            password=hash_password(password),
            role="admin",     # first admin bootstraps the system
            is_admin=True,
        ))
        await db.commit()
        print("CREATED")

asyncio.run(main())
EOF
)

case "$CREATED" in
    *CREATED*)
        echo "admin created: ${ADMIN_EMAIL}"
        printf '%s\n' "$ADMIN_PASSWORD" > .admin-password
        chmod 600 .admin-password
        ;;
    *EXISTS*) echo "admin ${ADMIN_EMAIL} already exists — leaving it alone" ;;
    *)        die "admin bootstrap failed:\n$CREATED" ;;
esac

# ── 5. Seed rates (pricing engine needs a populated rate table) ──────
say "Seeding the rate table"
if [ -f .admin-password ]; then
    SEED_PW="$(cat .admin-password)"
else
    SEED_PW="${ADMIN_PASSWORD}"
fi

$COMPOSE exec -T \
    -e SC_ADMIN_EMAIL="$ADMIN_EMAIL" \
    -e SC_ADMIN_PASSWORD="$SEED_PW" \
    backend python - <<'EOF' || warn "rate seeding failed — do it from the Rates page, or re-run this script"
import json, os, urllib.request

def post(path, data=None, token=None):
    req = urllib.request.Request(
        "http://localhost:8000" + path,
        data=json.dumps(data).encode() if data is not None else b"",
        headers={"Content-Type": "application/json",
                 **({"Authorization": "Bearer " + token} if token else {})},
        method="POST")
    return json.loads(urllib.request.urlopen(req, timeout=15).read() or b"{}")

tok = post("/auth/login", {"email": os.environ["SC_ADMIN_EMAIL"],
                           "password": os.environ["SC_ADMIN_PASSWORD"]})["access_token"]
print(post("/rates/seed", token=tok))
EOF

# ── 6. Smoke test over the public HTTPS URL ──────────────────────────
say "Smoke-testing https://${SITE_ADDRESS}"
echo "(Caddy may need up to ~60s on first run to obtain the certificate)"

TLS_OK=0
for _ in $(seq 1 30); do
    if curl -fsS --max-time 10 "https://${SITE_ADDRESS}/ready" 2>/dev/null | grep -q '"status":"ready"'; then
        TLS_OK=1; break
    fi
    printf '.'; sleep 5
done
echo

if [ "$TLS_OK" = 1 ]; then
    say "Deployment complete"
    echo "  URL:      https://${SITE_ADDRESS}"
    echo "  Login:    ${ADMIN_EMAIL}"
    if [ -f .admin-password ]; then
        echo "  Password: $(cat .admin-password)"
        echo
        echo "  Change this password in the app, then: rm .admin-password"
    fi
    echo
    echo "  Next: walk the smoke test in docs/DEPLOY.md §10 (especially the PDF"
    echo "        download), and set up database backups (§8) — nothing does yet."
else
    warn "The app is running, but HTTPS did not answer yet."
    echo "  Most common causes:"
    echo "    - ports 80/443 not open to the internet (cloud firewall / security group)"
    echo "    - DNS for ${SITE_ADDRESS} not resolving to this server"
    echo "  Inspect with:  $COMPOSE logs caddy --tail 40"
    echo "  Verify locally: curl -fsS http://127.0.0.1:8080/ready"
    exit 1
fi
